### PR TITLE
Add distributable build

### PR DESCRIPTION
**Pull request by deerob4**
The VS Code architecture for loading a script into a webview relies on a single distributable file to be created, so this PR adds a Webpack config for generating this. Once we have CI setup, we can do this automatically.

### CODE REVIEW

**Comment by Riphiphip** [comment]
@deerob4 Should be ready to merge now

**Comment by datenreisender** [comment]
The content of `dist/index.js` is now out of sync with the code in `src`, because you did not rebase the branch on master (or merge in master) and recreate `dist/index.js` before you merged this branch into master. Would be good if you could create another PR which does that.

**Comment by datenreisender** [comment]
Can we also automatically create TypeScript type definitions for `dist/index.js`, so that we do not need two compiled artifacts (`lib` and `dist`) but just one?

**Comment by Riphiphip** [comment]
I'll look into it

**Comment by Riphiphip** [comment]
Dist has been updated in #14, but I couldn't find a good way to generate typescript types. To be honest this was just quickly thrown together to make it possible for me to experiment with using the addon in a web-like context, and the whole build/distribute process should be looked into by someone who actually knows what they're doing

**Pull request merged**
